In [9]:
import pandas as pd
import numpy as np
reviews = pd.read_pickle("reviews.pickle")
products = pd.read_pickle("products.pickle")

In [10]:
products.head()

brand  \
asin                                 
616719923X                     NaN   
9742356831                Mae Ploy   
B00004S1C5   HIC Harold Import Co.   
B0000531B7                Powerbar   
B00005344V  Traditional Medicinals   

                                                   categories  \
asin                                                            
616719923X                         [[Grocery & Gourmet Food]]   
9742356831                         [[Grocery & Gourmet Food]]   
B00004S1C5  [[Grocery & Gourmet Food, Cooking & Baking, Fo...   
B0000531B7                         [[Grocery & Gourmet Food]]   
B00005344V                         [[Grocery & Gourmet Food]]   

                                                  description  \
asin                                                            
616719923X  Green Tea Flavor Kit Kat have quickly become t...   
9742356831  Used to make various curry soups and stir fry ...   
B00004S1C5  From Easter eggs to colorful cookies, Spectrum...   
B0000531B7                                                      
B00005344V  For nearly forty years, we&#x2019;ve been pass...   

                                                        imUrl  price  \
asin                                                                   
616719923X  http://ecx.images-amazon.com/images/I/51LdEao6...    NaN   
9742356831  http://ecx.images-amazon.com/images/I/41pQp67A...   7.23   
B00004S1C5  http://ecx.images-amazon.com/images/I/41F75K9F...   9.76   
B0000531B7  http://ecx.images-amazon.com/images/I/519SuVj1...  24.75   
B00005344V  http://ecx.images-amazon.com/images/I/51H54cd-...  21.74   

                                                      related  \
asin                                                            
616719923X  {'also_viewed': ['B0047YG5UY', 'B00FKQ6X46', '...   
9742356831  {'also_viewed': ['B000EI2LLO', 'B0035AV5II', '...   
B00004S1C5  {'also_viewed': ['B000FNM5PU', 'B0029YDR82', '...   
B0000531B7  {'also_viewed': ['B009VV7G60', 'B00DZGEY44', '...   
B00005344V  {'also_viewed': ['B00028N5Q6', 'B000CMIYWC', '...   

                                    salesRank  \
asin                                            
616719923X  {'Grocery & Gourmet Food': 37305}   
9742356831   {'Grocery & Gourmet Food': 3434}   
B00004S1C5         {'Kitchen & Dining': 4494}   
B0000531B7   {'Grocery & Gourmet Food': 2858}   
B00005344V   {'Grocery & Gourmet Food': 5034}   

                                                        title  
asin                                                           
616719923X  Japanese Kit Kat Maccha Green Tea Flavor (5 Ba...  
9742356831        Mae Ploy Thai Green Curry Paste - 14 oz jar  
B00004S1C5                  Ateco Food Coloring Kit, 6 colors  
B0000531B7  PowerBar Harvest Energy Bars, Double Chocolate...  
B00005344V  Traditional Medicinals Breathe Easy, 16-Count ...

In [11]:
products = products.dropna(subset = ["title","description"])
products.shape
from sklearn.feature_extraction.text import CountVectorizer
dtm = CountVectorizer(vocabulary=["green", "tea", "curry", "kit"]).fit_transform(products.title)


In [13]:
x = dtm[0,:].toarray()
y = dtm[0,:].toarray()
x,y

(array([[1, 1, 0, 1]]), array([[1, 1, 0, 1]]))

In [14]:
x = np.squeeze(x); y=np.squeeze(y)
x,y

(array([1, 1, 0, 1]), array([1, 1, 0, 1]))

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(dtm)

In [17]:
sim[0,:].argsort()[-10:]

array([2838, 2839,  257, 8180, 6916, 5210, 7001, 5201, 5956,    0])

In [18]:
products.ix[5956].title, products.ix[0].title

('Meltykiss Matcha Green Tea Chocolate By Meiji From Japan 60g',
 'Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)')

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
tf = TfidfVectorizer(ngram_range=(1, 3),stop_words='english')
dtm = tf.fit_transform(products.description + products.title)
sim = linear_kernel(dtm)

In [53]:
sim[0,:].argsort()[-10:]

array([7101, 1704, 2402, 3645, 3648, 3011, 6631, 3823, 7046,    0])

In [35]:
products.ix[3823].title, products.ix[0].title

('Kit Kat Candy Bar, Crisp Wafers in White Chocolate, 1.5-Ounce Bars (Pack of 24)',
 'Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)')

In [36]:
import pandas as pd
import numpy as np
reviews = pd.read_pickle("reviews.pickle")

In [37]:
ratings = reviews[reviews.reviewerID == "A3P51YKG3BCT4K"][["asin", "overall"]]
ratings.overall -= ratings.overall.mean()
ratings

asin  overall
23673  B000HDJXLW     -0.4
28152  B000LKXRNQ      0.6
28501  B000LKZ9KK      0.6
63226  B001SB4YPC     -0.4
79633  B00374W630     -0.4

In [38]:
products = pd.read_pickle("products.pickle")
products = products.join(ratings.set_index("asin"))
products = products.dropna(subset=["title", "description"])
# see products with a rating:
products.dropna(subset=["overall"])

brand                  categories  \
asin                                                  
B000HDJXLW    Muir Glen  [[Grocery & Gourmet Food]]   
B000LKXRNQ    Vita Coco  [[Grocery & Gourmet Food]]   
B000LKZ9KK    Muir Glen  [[Grocery & Gourmet Food]]   
B001SB4YPC      WEL PAC  [[Grocery & Gourmet Food]]   
B00374W630  Old El Paso  [[Grocery & Gourmet Food]]   

                                                  description  \
asin                                                            
B000HDJXLW                                                      
B000LKXRNQ  The Vita Coco brand launched in 2004 and was i...   
B000LKZ9KK                                                      
B001SB4YPC  Wel Pac Noodles Yokogiri Udon is the smoothest...   
B00374W630  Old El Paso Fat Free Refried Beans 16 oz (Pack...   

                                                        imUrl  price  \
asin                                                                   
B000HDJXLW  http://ecx.images-amazon.com/images/I/51SPGYND...  31.00   
B000LKXRNQ  http://ecx.images-amazon.com/images/I/41yCAH%2...  19.99   
B000LKZ9KK  http://ecx.images-amazon.com/images/I/51pLCmCW...  22.99   
B001SB4YPC  http://ecx.images-amazon.com/images/I/416Er3CN...  19.50   
B00374W630  http://ecx.images-amazon.com/images/I/61a6NQWX...  30.89   

                                                      related  \
asin                                                            
B000HDJXLW  {'also_viewed': ['B000LKZ9IC', 'B000LKZ9KK', '...   
B000LKXRNQ  {'also_viewed': ['B008774SUQ', 'B008UQLZ5A', '...   
B000LKZ9KK  {'also_viewed': ['B000LKZ9IC', 'B000HDJXLW', '...   
B001SB4YPC  {'also_viewed': ['B007W0D0HQ', 'B000LKX6RS', '...   
B00374W630  {'also_viewed': ['B005G2FCI2', 'B005EKI710', '...   

                                    salesRank  \
asin                                            
B000HDJXLW   {'Grocery & Gourmet Food': 3429}   
B000LKXRNQ    {'Grocery & Gourmet Food': 312}   
B000LKZ9KK   {'Grocery & Gourmet Food': 4654}   
B001SB4YPC  {'Grocery & Gourmet Food': 71695}   
B00374W630   {'Grocery & Gourmet Food': 8510}   

                                                        title  overall  
asin                                                                    
B000HDJXLW  Muir Glen Organic Diced Tomatoes, No Salt, 14....     -0.4  
B000LKXRNQ  Vita Coco Coconut Water with Pineapple, 11.1-O...      0.6  
B000LKZ9KK  Muir Glen Organic Tomatoes, Diced, 14.5-Ounce ...      0.6  
B001SB4YPC  Wel Pac Noodles Yokogiri Udon, 10-Ounce (Pack ...     -0.4  
B00374W630  Old El Paso Refried Beans, Fat Free, 16-Ounce ...     -0.4

In [105]:
products.dropna(subset=["overall"]).title

asin
B000HDJXLW    Muir Glen Organic Diced Tomatoes, No Salt, 14....
B000LKXRNQ    Vita Coco Coconut Water with Pineapple, 11.1-O...
B000LKZ9KK    Muir Glen Organic Tomatoes, Diced, 14.5-Ounce ...
B001SB4YPC    Wel Pac Noodles Yokogiri Udon, 10-Ounce (Pack ...
B00374W630    Old El Paso Refried Beans, Fat Free, 16-Ounce ...
Name: title, dtype: object

In [112]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
tf = TfidfVectorizer(stop_words='english')
dtm = tf.fit_transform(products.description + products.title)

In [113]:
sim = cosine_similarity(dtm)
#只有那五条的相似度
sims = sim[:,np.array(products.overall.notnull())]

In [114]:
pred = sims.dot(products.overall.dropna())
products["pred"] = pred
products_new = products.sort_values(by = "pred",ascending = False)

In [115]:
products_new #所以要推荐，就要推荐0.6和0.4左右的

brand                  categories  \
asin                                                         
B000LKXRNQ           Vita Coco  [[Grocery & Gourmet Food]]   
B001CBRMTS                 NaN  [[Grocery & Gourmet Food]]   
B000LKZLCQ                 NaN  [[Grocery & Gourmet Food]]   
B00101S5SC                 NaN  [[Grocery & Gourmet Food]]   
B001VDXO3K                 NaN  [[Grocery & Gourmet Food]]   
B001NJGA06           Vita Coco  [[Grocery & Gourmet Food]]   
B005BHIESC           Vita Coco  [[Grocery & Gourmet Food]]   
B007JHXQQC           Vita Coco  [[Grocery & Gourmet Food]]   
B001UJIFRU                 NaN  [[Grocery & Gourmet Food]]   
B00CIX6P1U           Vita Coco  [[Grocery & Gourmet Food]]   
B001NJGA7Y           Vita Coco  [[Grocery & Gourmet Food]]   
B000LKZ9KK           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKZ9IC           Muir Glen  [[Grocery & Gourmet Food]]   
B000HDJXLW           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKVH9W           Muir Glen  [[Grocery & Gourmet Food]]   
B001NJI7GQ           Vita Coco  [[Grocery & Gourmet Food]]   
B005G2FC50          CoCo Libre  [[Grocery & Gourmet Food]]   
B000LKZ9JG           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKTZSM           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKVH8S           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKXG64           Muir Glen  [[Grocery & Gourmet Food]]   
B000IZ0OB2    Caffe D&#39;Vita  [[Grocery & Gourmet Food]]   
B000IZ0OC6    Caffe D&#39;Vita  [[Grocery & Gourmet Food]]   
B001PI32BA                 NaN  [[Grocery & Gourmet Food]]   
B000LKXFMO           Muir Glen  [[Grocery & Gourmet Food]]   
B0012HEVRI                 NaN  [[Grocery & Gourmet Food]]   
B000LKXFTC           Muir Glen  [[Grocery & Gourmet Food]]   
B000LKZ9Q4           Muir Glen  [[Grocery & Gourmet Food]]   
B0012HEVNM           Muir Glen  [[Grocery & Gourmet Food]]   
B0012HCR9C           Muir Glen  [[Grocery & Gourmet Food]]   
...                        ...                         ...   
B00AQM76K4         Lipton Soup  [[Grocery & Gourmet Food]]   
B001E5E2AO                 NaN  [[Grocery & Gourmet Food]]   
B001E5E2AE                 NaN  [[Grocery & Gourmet Food]]   
B000LKX1KU                Eden  [[Grocery & Gourmet Food]]   
B0000GHNTU         El Yucateco  [[Grocery & Gourmet Food]]   
B0002YGSJQ               House  [[Grocery & Gourmet Food]]   
B00DBSG2WI                 NaN  [[Grocery & Gourmet Food]]   
B004VLVJP4  Bob&#39;s Red Mill  [[Grocery & Gourmet Food]]   
B0002YGSAU             S&amp;B  [[Grocery & Gourmet Food]]   
B004VLVJB8                 NaN  [[Grocery & Gourmet Food]]   
B005EKI6ZW                 NaN  [[Grocery & Gourmet Food]]   
B007UPVFZW             Menraku  [[Grocery & Gourmet Food]]   
B000FI701Y                 NaN  [[Grocery & Gourmet Food]]   
B000G18NRU   Amy&#39;s Organic  [[Grocery & Gourmet Food]]   
B000FICDO8                 NaN  [[Grocery & Gourmet Food]]   
B000FIAWVE                 NaN  [[Grocery & Gourmet Food]]   
B00480KJWC           Shirakiku  [[Grocery & Gourmet Food]]   
B000LKX6R8            Hakubaku  [[Grocery & Gourmet Food]]   
B001M1Z14Q               Myojo  [[Grocery & Gourmet Food]]   
B000G18NS4   Amy&#39;s Organic  [[Grocery & Gourmet Food]]   
B0040Q0EJW                 JFC  [[Grocery & Gourmet Food]]   
B000G176DW   Amy&#39;s Organic  [[Grocery & Gourmet Food]]   
B003JA5KH6                 NaN  [[Grocery & Gourmet Food]]   
B000LKX6RS            Hakubaku  [[Grocery & Gourmet Food]]   
B007V4UWDI             Menraku  [[Grocery & Gourmet Food]]   
B000EFFTRU         Old El Paso  [[Grocery & Gourmet Food]]   
B000EFHSUQ         Old El Paso  [[Grocery & Gourmet Food]]   
B000EMK4IW         Old El Paso  [[Grocery & Gourmet Food]]   
B00374W630         Old El Paso  [[Grocery & Gourmet Food]]   
B001SB4YPC             WEL PAC  [[Grocery & Gourmet Food]]   

                                                  description  \
asin                                                 

In [117]:
import numpy as np
from numpy import NAN
#如果有缺失值，那该怎么办
#协同过滤

In [121]:
m = np.matrix([[7,6,7,4,5,4],[6,7,NAN,4,3,4],[NAN,3,3,1,1,NAN],[1,2,2,3,3,4],[1,NAN,1,2,3,3]])
m

matrix([[  7.,   6.,   7.,   4.,   5.,   4.],
        [  6.,   7.,  nan,   4.,   3.,   4.],
        [ nan,   3.,   3.,   1.,   1.,  nan],
        [  1.,   2.,   2.,   3.,   3.,   4.],
        [  1.,  nan,   1.,   2.,   3.,   3.]])

In [122]:
mu = np.nanmean(m,axis = 1)
mu

matrix([[ 5.5],
        [ 4.8],
        [ 2. ],
        [ 2.5],
        [ 2. ]])

In [123]:
mc = m - mu
mc

matrix([[ 1.5,  0.5,  1.5, -1.5, -0.5, -1.5],
        [ 1.2,  2.2,  nan, -0.8, -1.8, -0.8],
        [ nan,  1. ,  1. , -1. , -1. ,  nan],
        [-1.5, -0.5, -0.5,  0.5,  0.5,  1.5],
        [-1. ,  nan, -1. ,  0. ,  1. ,  1. ]])

In [125]:
u = mc[0,:]
v = mc[2,:]
u = np.ravel(u)
v = np.ravel(v)

[ 1.5  0.5  1.5 -1.5 -0.5 -1.5]
[ nan   1.   1.  -1.  -1.  nan]


In [129]:
Iuv = np.logical_and(np.isfinite(u), np.isfinite(v))
#取两个的交集

In [134]:
#平方和，也就是每个的长度
norm = np.sqrt(np.sum(np.square(u[Iuv]))*np.sum(np.square(v[Iuv])))

In [135]:
u[Iuv].dot(v[Iuv]) / norm

0.89442719099991586

In [136]:
def sparse_correlation(u,v):
    u = np.ravel(u)
    v = np.ravel(v)
    Iuv = np.logical_and(np.isfinite(u), np.isfinite(v))
    norm = np.sqrt(np.sum(np.square(u[Iuv]))*np.sum(np.square(v[Iuv])))
    return u[Iuv].dot(v[Iuv]) / norm

In [137]:
sparse_correlation(u,v)

0.89442719099991586

In [140]:
#为这个矩阵的每行都计算它的相似值
sim = np.zeros(25).reshape(5,5)
for i in range(5):
    for j in range(5):
        sim[i,j] = sparse_correlation(mc[i,:],mc[j,:])
sim

array([[ 1.        ,  0.70066562,  0.89442719, -0.8992288 , -0.82199494],
       [ 0.70066562,  1.        ,  0.93847426, -0.71713717, -0.89866916],
       [ 0.89442719,  0.93847426,  1.        , -1.        , -0.81649658],
       [-0.8992288 , -0.71713717, -1.        ,  1.        ,  0.87287156],
       [-0.82199494, -0.89866916, -0.81649658,  0.87287156,  1.        ]])

In [164]:
mc_filled = np.nan_to_num(mc)
#nan = 0 

In [165]:
ratings

matrix([[ 1.5,  0.5,  1.5, -1.5, -0.5, -1.5],
        [ 1.2,  2.2,  0. , -0.8, -1.8, -0.8],
        [ 0. ,  1. ,  1. , -1. , -1. ,  0. ],
        [-1.5, -0.5, -0.5,  0.5,  0.5,  1.5],
        [-1. ,  0. , -1. ,  0. ,  1. ,  1. ]])

In [166]:
np.fill_diagonal(sim,0)

In [167]:
sim

array([[ 0.        ,  0.70066562,  0.89442719, -0.8992288 , -0.82199494],
       [ 0.70066562,  0.        ,  0.93847426, -0.71713717, -0.89866916],
       [ 0.89442719,  0.93847426,  0.        , -1.        , -0.81649658],
       [-0.8992288 , -0.71713717, -1.        ,  0.        ,  0.87287156],
       [-0.82199494, -0.89866916, -0.81649658,  0.87287156,  0.        ]])

In [168]:
pred = mu + sim.dot(mc_filled) / np.abs(sim).sum(axis=1)[:, None]

In [170]:
pred.round(1)

array([[ 6.4,  6.4,  6.2,  4.9,  4.5,  4.7],
       [ 5.7,  5.3,  5.8,  4.1,  4. ,  3.9],
       [ 3.3,  2.8,  2.7,  1.3,  1.1,  0.8],
       [ 1.6,  1.6,  1.6,  3.3,  3.5,  3.3],
       [ 0.9,  0.9,  1.3,  2.9,  3. ,  3. ]])

matrix([[  7.,   6.,   7.,   4.,   5.,   4.],
        [  6.,   7.,  nan,   4.,   3.,   4.],
        [ nan,   3.,   3.,   1.,   1.,  nan],
        [  1.,   2.,   2.,   3.,   3.,   4.],
        [  1.,  nan,   1.,   2.,   3.,   3.]])

In [172]:
import numpy as np
m = np.matrix([[1,1,1,0,0],[0,0,1,1,0],[1,1,0,0,1],[1,1,1,0,1]])
m

matrix([[1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0],
        [1, 1, 0, 0, 1],
        [1, 1, 1, 0, 1]])

In [181]:
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics.pairwise import cosine_similarity
print(pairwise_distances(m,metric = "cosine"))

[[ 0.          0.59175171  0.33333333  0.1339746 ]
 [ 0.59175171  0.          1.          0.64644661]
 [ 0.33333333  1.          0.          0.1339746 ]
 [ 0.1339746   0.64644661  0.1339746   0.        ]]


In [184]:
np.fill_diagonal(sim, 0)
total_weights = sim.sum(axis=1)
#sim[0, :].dot(m[:, 4]) / total_weights[0]

In [185]:
total_weights

array([-0.12613093,  0.02333356,  0.01640487, -1.74349441, -1.66428912])