In [152]:
import pandas as pd
import numpy as np
reviews = pd.read_pickle("reviews.pickle")
products = pd.read_pickle("products.pickle")

In [153]:
products.shape

(8713, 8)

In [154]:
products_d = products.dropna(subset = ["title","description"])

In [155]:
products_d.head()

brand  \
asin                                 
616719923X                     NaN   
9742356831                Mae Ploy   
B00004S1C5   HIC Harold Import Co.   
B0000531B7                Powerbar   
B00005344V  Traditional Medicinals   

                                                   categories  \
asin                                                            
616719923X                         [[Grocery & Gourmet Food]]   
9742356831                         [[Grocery & Gourmet Food]]   
B00004S1C5  [[Grocery & Gourmet Food, Cooking & Baking, Fo...   
B0000531B7                         [[Grocery & Gourmet Food]]   
B00005344V                         [[Grocery & Gourmet Food]]   

                                                  description  \
asin                                                            
616719923X  Green Tea Flavor Kit Kat have quickly become t...   
9742356831  Used to make various curry soups and stir fry ...   
B00004S1C5  From Easter eggs to colorful cookies, Spectrum...   
B0000531B7                                                      
B00005344V  For nearly forty years, we&#x2019;ve been pass...   

                                                        imUrl  price  \
asin                                                                   
616719923X  http://ecx.images-amazon.com/images/I/51LdEao6...    NaN   
9742356831  http://ecx.images-amazon.com/images/I/41pQp67A...   7.23   
B00004S1C5  http://ecx.images-amazon.com/images/I/41F75K9F...   9.76   
B0000531B7  http://ecx.images-amazon.com/images/I/519SuVj1...  24.75   
B00005344V  http://ecx.images-amazon.com/images/I/51H54cd-...  21.74   

                                                      related  \
asin                                                            
616719923X  {'also_viewed': ['B0047YG5UY', 'B00FKQ6X46', '...   
9742356831  {'bought_together': ['B000EI2LLO', 'B000EICISA...   
B00004S1C5  {'bought_together': ['B0000CFMLT'], 'also_view...   
B0000531B7  {'bought_together': ['B009VV7G60', 'B00DZGEY44...   
B00005344V  {'bought_together': ['B0009F3POO', 'B0009F3POE...   

                                    salesRank  \
asin                                            
616719923X  {'Grocery & Gourmet Food': 37305}   
9742356831   {'Grocery & Gourmet Food': 3434}   
B00004S1C5         {'Kitchen & Dining': 4494}   
B0000531B7   {'Grocery & Gourmet Food': 2858}   
B00005344V   {'Grocery & Gourmet Food': 5034}   

                                                        title  
asin                                                           
616719923X  Japanese Kit Kat Maccha Green Tea Flavor (5 Ba...  
9742356831        Mae Ploy Thai Green Curry Paste - 14 oz jar  
B00004S1C5                  Ateco Food Coloring Kit, 6 colors  
B0000531B7  PowerBar Harvest Energy Bars, Double Chocolate...  
B00005344V  Traditional Medicinals Breathe Easy, 16-Count ...

In [156]:
from sklearn.feature_extraction.text import CountVectorizer
dtm = CountVectorizer(vocabulary = ["green","tea","curry","kit"]).fit_transform(products_d.title)

In [119]:
x = dtm[0,:].toarray()
y = dtm[1,:].toarray()

In [120]:
x = np.squeeze(x);y = np.squeeze(y)
x,y

(array([1, 1, 0, 1]), array([1, 0, 1, 0]))

In [121]:
from math import sqrt
x.dot(y) / (sqrt(x.dot(x)) * sqrt(y.dot(y)))
x.dot(y) / sqrt((x.dot(x)) * y.dot(y))

0.40824829046386307

In [122]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(dtm)

In [123]:
sim[0,:].argsort()[-10:]

array([2838, 2839,  257, 8180, 6916, 5210, 7001, 5201, 5956,    0])

In [124]:
print(products_d.ix[2838].title)
print(products_d.ix[0].title)

DoMatcha Green Tea, Organic Matcha, 1.0-Ounce Tin
Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)


In [125]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

tf = TfidfVectorizer(ngram_range = (1,3),stop_words = 'english')
dtm = tf.fit_transform(products_d.description + products_d.title)
sim = linear_kernel(dtm)

In [126]:
sim.shape

(8470, 8470)

In [127]:
import pandas as pd
import numpy as np
reviews = pd.read_pickle("reviews.pickle")

In [128]:
ratings = reviews[reviews.reviewerID == "A3P51YKG3BCT4K"][["asin","overall"]]

In [129]:
ratings

asin  overall
23673  B000HDJXLW      3.0
28152  B000LKXRNQ      4.0
28501  B000LKZ9KK      4.0
63226  B001SB4YPC      3.0
79633  B00374W630      3.0

In [130]:
products = pd.read_pickle("products.pickle")
products = products.join(ratings.set_index("asin"))

In [131]:
products

brand  \
asin                                    
616719923X                        NaN   
9742356831                   Mae Ploy   
B00004S1C5      HIC Harold Import Co.   
B0000531B7                   Powerbar   
B00005344V     Traditional Medicinals   
B0000537AF                        NaN   
B00005C2M2  American Outdoor Products   
B00006IUTN                    Melitta   
B0000CD06J                      Cafix   
B0000CCZYY                      Panda   
B0000CDBQN     Magic Seasoning Blends   
B0000CDEPD                    Rodelle   
B0000CETGM  Jamaica Standard Products   
B0000CFLIL                    Melitta   
B0000CFLCT                    Melitta   
B0000CFN0Y                     Wilton   
B0000CFPI2                      Nesco   
B0000CH39R          See&#39;s Candies   
B0000CNU1X                    Unknown   
B0000CNU15                    Unknown   
B0000CNU1S                    DYNASTY   
B0000DANYR               Laci Le Beau   
B0000DBN2I                       TAZO   
B0000DBN1L                       TAZO   
B0000DC2VI          Harney &amp; Sons   
B0000DBN1H                       TAZO   
B0000DD8V3                      Bells   
B0000DGF9V                        NaN   
B0000DGDMO                      Orbit   
B0000DI085             Simply Organic   
...                               ...   
B00HSYVFQY                        NaN   
B00HXIXWKM                        NaN   
B00HYO5NAM                        NaN   
B00I08JNWU                        NaN   
B00I08JKI2                     Keurig   
B00I1MSJO8                 Crazy Cups   
B00I33696K                        NaN   
B00I8Q2BVO                        NaN   
B00ID9VSOM                        NaN   
B00IDCFXFE                        NaN   
B00IDXROMS                        NaN   
B00IFHD01G                        NaN   
B00IJ4JBJA            Coffee Blenders   
B00IP6Y21E                        NaN   
B00IRFM1JS                        NaN   
B00IRL93SY                        NaN   
B00ISMP3YA                        NaN   
B00ISQD2QM             Nescaf&eacute;   
B00ISVHJ3Y       Wholesome Sweeteners   
B00IV2XZWY      Pamela&#39;s Products   
B00IVT3LLW                        NaN   
B00IWBMCMS              The Spice Lab   
B00J9IUCHA                        NaN   
B00JAXNMRG                      Wonka   
B00JEL3N1E                        NaN   
B00JGPG60I                    Enfamil   
B00JL6LTMW                        NaN   
B00K00H9I6                        NaN   
B00KC0LGI8                        NaN   
B00KCJRVO2                        NaN   

                                                   categories  \
asin                                                            
616719923X                         [[Grocery & Gourmet Food]]   
9742356831                         [[Grocery & Gourmet Food]]   
B00004S1C5  [[Grocery & Gourmet Food, Cooking & Baking, Fo...   
B0000531B7                         [[Grocery & Gourmet Food]]   
B00005344V                         [[Grocery & Gourmet Food]]   
B0000537AF                         [[Grocery & Gourmet Food]]   
B00005C2M2                         [[Grocery & Gourmet Food]]   
B00006IUTN                         [[Grocery & Gourmet Food]]   
B0000CD06J  [[Grocery & Gourmet Food, Beverages, Coffee, C...   
B0000CCZYY                         [[Grocery & Gourmet Food]]   
B0000CDBQN                         [[Grocery & Gourmet Food]]   
B0000CDEPD                         [[Grocery & Gourmet Food]]   
B0000CETGM                         [[Grocery & Gourmet Food]]   
B0000CFLIL                         [[Grocery & Gourmet Food]]   
B0000CFLCT                         [[Grocery & Gourmet Food]]   
B0000CFN0Y  [[Grocery & Gourmet Food, Cooking & Baking, Fr...   
B0000CFPI2  [[Grocery & Gourmet Food, Snack Foods, Jerky &...   
B0000CH39R                         [[Grocery & Gourmet Food]]   
B0000CNU1X                         [[Grocery & Gourmet Food]]   
B0000CNU15                         [[Grocery & Gourmet Food]]   
B0000CNU1S        

In [132]:
products_d = products.dropna(subset = ["title","description"])

In [133]:
products_d.dropna(subset=["overall"])

brand                  categories  \
asin                                                  
B000HDJXLW    Muir Glen  [[Grocery & Gourmet Food]]   
B000LKXRNQ    Vita Coco  [[Grocery & Gourmet Food]]   
B000LKZ9KK    Muir Glen  [[Grocery & Gourmet Food]]   
B001SB4YPC      WEL PAC  [[Grocery & Gourmet Food]]   
B00374W630  Old El Paso  [[Grocery & Gourmet Food]]   

                                                  description  \
asin                                                            
B000HDJXLW                                                      
B000LKXRNQ  The Vita Coco brand launched in 2004 and was i...   
B000LKZ9KK                                                      
B001SB4YPC  Wel Pac Noodles Yokogiri Udon is the smoothest...   
B00374W630  Old El Paso Fat Free Refried Beans 16 oz (Pack...   

                                                        imUrl  price  \
asin                                                                   
B000HDJXLW  http://ecx.images-amazon.com/images/I/51SPGYND...  31.00   
B000LKXRNQ  http://ecx.images-amazon.com/images/I/41yCAH%2...  19.99   
B000LKZ9KK  http://ecx.images-amazon.com/images/I/51pLCmCW...  22.99   
B001SB4YPC  http://ecx.images-amazon.com/images/I/416Er3CN...  19.50   
B00374W630  http://ecx.images-amazon.com/images/I/61a6NQWX...  30.89   

                                                      related  \
asin                                                            
B000HDJXLW  {'bought_together': ['B000LKZ9Q4', 'B000LKXFMO...   
B000LKXRNQ  {'bought_together': ['B007PE7ANY', 'B008JKU2CO...   
B000LKZ9KK  {'bought_together': ['B000LKXG64', 'B000LKZ9IC...   
B001SB4YPC  {'bought_together': ['B000LKX6R8', 'B0002IZCYY...   
B00374W630  {'bought_together': ['B005G2FCI2', 'B0019RLJV2...   

                                    salesRank  \
asin                                            
B000HDJXLW   {'Grocery & Gourmet Food': 3429}   
B000LKXRNQ    {'Grocery & Gourmet Food': 312}   
B000LKZ9KK   {'Grocery & Gourmet Food': 4654}   
B001SB4YPC  {'Grocery & Gourmet Food': 71695}   
B00374W630   {'Grocery & Gourmet Food': 8510}   

                                                        title  overall  
asin                                                                    
B000HDJXLW  Muir Glen Organic Diced Tomatoes, No Salt, 14....      3.0  
B000LKXRNQ  Vita Coco Coconut Water with Pineapple, 11.1-O...      4.0  
B000LKZ9KK  Muir Glen Organic Tomatoes, Diced, 14.5-Ounce ...      4.0  
B001SB4YPC  Wel Pac Noodles Yokogiri Udon, 10-Ounce (Pack ...      3.0  
B00374W630  Old El Paso Refried Beans, Fat Free, 16-Ounce ...      3.0

In [143]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
tf = TfidfVectorizer(stop_words="english")
dtm = tf.fit_transform(products_d.description + products_d.title)

In [144]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(dtm)

In [145]:
sim[0,].argsort()[-10:]

array([6681, 3011, 2402, 2237, 1704, 3645, 3648, 6631, 3823,    0])

In [146]:
products_d.ix[0].description + products_d.ix[0].title

"Green Tea Flavor Kit Kat have quickly become the most sought after snack from Japan. Here are a limited supply of Maccha Green Tea flavored Kit Kat that you would not want to miss. These epic snacks have a sweet maccha green tea flavor mixed with creamy white chocolate, on a crispy wafer that Nestle's has perfected. Each bag contains 12 individually wrapped bars.Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)"

_Kit Kat _creamy white chocolate _bar

In [147]:
products_d.ix[3823].description + products_d.ix[3823].title

'Kit Kat Candy Bar, Crisp Wafers in White Chocolate, 1.5-Ounce Bars (Pack of 24)'

In [148]:
sims = sim[:,np.array(products_d.overall.notnull())] #这个人选择这五个商品的similarities

In [149]:
pred = sims.dot(products_d.overall.dropna())

In [150]:
products_d["pred"] = pred

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [151]:
dtm

<8470x18835 sparse matrix of type '<class 'numpy.float64'>'
	with 345854 stored elements in Compressed Sparse Row format>